import { loadEnvironment, type Environment } from '../../src/config/environment.js';

export function createTestEnvironment(
  databaseUrl = 'postgresql://test:test@127.0.0.1:55432/fab_control_test',
  defaultTenantId = '00000000-0000-4000-8000-000000000001',
): Environment {
  return loadEnvironment({
    NODE_ENV: 'test',
    HOST: '127.0.0.1',
    PORT: '3333',
    LOG_LEVEL: 'silent',
    TRUST_PROXY: 'false',
    BODY_LIMIT_BYTES: '1048576',
    CORS_ALLOWED_ORIGINS: 'http://127.0.0.1:5173',
    OPENAPI_ENABLED: 'false',
    STORAGE_LOCAL_ROOT: './var/test-private-storage',
    STORAGE_MAX_EVIDENCE_BYTES: '6291456',
    DATABASE_URL: databaseUrl,
    DATABASE_SSL_MODE: 'disable',
    DATABASE_POOL_MAX: '4',
    DATABASE_IDLE_TIMEOUT_MS: '5000',
    DATABASE_CONNECTION_TIMEOUT_MS: '5000',
    DATABASE_STATEMENT_TIMEOUT_MS: '15000',
    DEFAULT_TENANT_ID: defaultTenantId,
    APP_ENVIRONMENT: 'DEVELOPMENT',
    APP_RELEASE_VERSION: '1.4.0',
    API_VERSION: '2.0.0',
    SCHEMA_VERSION: 'postgres-0017',
    CONTRACT_VERSION: '2.0.0',
    FRONTEND_VERSION: '1.4.0',
    AUTH_SESSION_HOURS: '8',
    AUTH_FIRST_ACCESS_MINUTES: '15',
    AUTH_MAINTENANCE_SESSION_MINUTES: '30',
    AUTH_MAX_FAILED_ATTEMPTS: '5',
    AUTH_LOCK_MINUTES: '15',
    AUTH_RECOVERY_COOLDOWN_MINUTES: '10',
    AUTH_PASSWORD_PEPPER: 'test-password-pepper-with-32-characters-minimum',
    AUTH_RECOVERY_HMAC_SECRET: 'test-recovery-secret-with-32-characters-minimum',
    AUTH_MAINTENANCE_HMAC_SECRET: 'test-maintenance-secret-with-32-characters-minimum',
  });
}
