import ExcelJS from 'exceljs';

import { sourceSheetContracts } from '../../src/infrastructure/migration/source-contract.js';

type FixtureScalar = string | number | boolean | null;
type FixtureRow = Readonly<Record<string, FixtureScalar>>;

const at = '2026-08-04T12:00:00-03:00';
const later = '2026-08-04T13:00:00-03:00';

const rows: Readonly<Record<string, readonly FixtureRow[]>> = {
  config: [
    {
      chave: 'EMPRESA_NOME',
      valor: 'Fab Control Migração',
      descricao: 'Identidade',
      atualizado_em: at,
    },
  ],
  usuarios: [
    {
      id: 'USR-ADMIN-001',
      nome: 'Admin Migração',
      email: 'admin.migration@example.test',
      perfil: 'ADMIN',
      status: 'ACTIVE',
      pin_hash: 'legacy-pin',
      criado_em: at,
      atualizado_em: at,
      matricula: 'MIG-ADMIN-001',
      senha_hash: 'legacy-password',
      primeiro_acesso: true,
      tentativas_login: 0,
      bloqueado_ate: null,
      ultimo_login_em: null,
      senha_atualizada_em: at,
      recuperacao_referencia: null,
      recuperacao_solicitada_em: null,
      area_id: null,
      cargo_id: null,
      especialidades_json: '[]',
      escopo_ids_json: '[]',
    },
    {
      id: 'USR-QUALITY-001',
      nome: 'Qualidade Migração',
      email: 'quality.migration@example.test',
      perfil: 'GESTOR',
      status: 'ACTIVE',
      pin_hash: null,
      criado_em: at,
      atualizado_em: at,
      matricula: 'MIG-QUALITY-001',
      senha_hash: 'legacy-password',
      primeiro_acesso: true,
      tentativas_login: 0,
      bloqueado_ate: null,
      ultimo_login_em: null,
      senha_atualizada_em: at,
      recuperacao_referencia: null,
      recuperacao_solicitada_em: null,
      area_id: 'AREA-QUALITY',
      cargo_id: 'ROLE-INSPECTOR',
      especialidades_json: '["qualidade"]',
      escopo_ids_json: '["ASSET-001"]',
    },
    {
      id: 'USR-OPERATOR-001',
      nome: 'Operador Migração',
      email: 'operator.migration@example.test',
      perfil: 'OPERADOR',
      status: 'ACTIVE',
      pin_hash: null,
      criado_em: at,
      atualizado_em: at,
      matricula: 'MIG-OPERATOR-001',
      senha_hash: 'legacy-password',
      primeiro_acesso: true,
      tentativas_login: 0,
      bloqueado_ate: null,
      ultimo_login_em: null,
      senha_atualizada_em: at,
      recuperacao_referencia: null,
      recuperacao_solicitada_em: null,
      area_id: null,
      cargo_id: null,
      especialidades_json: '[]',
      escopo_ids_json: '["ASSET-001"]',
    },
  ],
  sessoes: [
    {
      token: 'LEGACY-SESSION-001',
      usuario_id: 'USR-ADMIN-001',
      perfil: 'ADMIN',
      status: 'ACTIVE',
      criado_em: at,
      expira_em: later,
      ultimo_uso_em: at,
      user_agent: 'migration-fixture',
      escopo: 'ADMIN',
      expira_ms: 3600000,
      revogado_em: null,
      motivo_revogacao: null,
      janela_id: 'WINDOW-001',
      ambiente: 'HOMOLOGATION',
      tenant_id: 'LEGACY-TENANT',
    },
  ],
  plantas: [
    {
      id: 'PLANT-001',
      tag: 'PL-01',
      nome: 'Planta Teste',
      status: 'ACTIVE',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  setores: [
    {
      id: 'SECTOR-001',
      planta_id: 'PLANT-001',
      tag: 'ST-01',
      nome: 'Produção',
      status: 'ACTIVE',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  linhas: [
    {
      id: 'LINE-001',
      setor_id: 'SECTOR-001',
      tag: 'LN-01',
      nome: 'Linha 1',
      status: 'ACTIVE',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  ativos: [
    {
      id: 'ASSET-001',
      linha_id: 'LINE-001',
      tag: 'EQ-001',
      qr_payload: 'FAB:ASSET:EQ-001',
      nome: 'Motor principal',
      tipo: 'MOTOR',
      criticidade: 'HIGH',
      status: 'OPERATING',
      saude_pct: 92,
      horimetro_atual: 1200,
      fabricante: 'Fab Test',
      modelo: 'M-1',
      numero_serie: 'SN-001',
      localizacao_tecnica: 'Linha 1',
      criado_em: at,
      atualizado_em: at,
      horimetro_modo: 'MANUAL',
      horimetro_atualizado_em: at,
      horimetro_base_servico: 1000,
      horimetro_base_servico_em: at,
    },
  ],
  componentes: [
    {
      id: 'COMP-001',
      ativo_id: 'ASSET-001',
      tag: 'CP-001',
      qr_payload: 'FAB:COMPONENT:CP-001',
      nome: 'Rolamento',
      tipo: 'BEARING',
      criticidade: 'HIGH',
      status: 'OPERATING',
      vida_util_horas: 5000,
      vida_util_dias: 365,
      horas_acumuladas: 1200,
      instalado_em: at,
      fabricante: 'Fab Test',
      modelo: 'R-1',
      numero_serie: 'CP-SN-001',
      localizacao_tecnica: 'Motor principal',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  materiais: [
    {
      id: 'MAT-001',
      sku: 'SKU-001',
      nome: 'Graxa industrial',
      unidade: 'kg',
      estoque_atual: 10,
      estoque_minimo: 2,
      status: 'ACTIVE',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  planos_manutencao: [
    {
      id: 'PLAN-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      nome: 'Inspeção do motor',
      tipo: 'PREVENTIVE',
      criticidade: 'HIGH',
      gatilho_tipo: 'MANUAL',
      gatilho_valor: null,
      unidade: null,
      recorrencia_dias: 30,
      tempo_estimado_min: 45,
      requer_bloqueio: true,
      requer_evidencia: true,
      max_sessoes: 1,
      status: 'ACTIVE',
      ultimo_disparo_em: null,
      criado_em: at,
      atualizado_em: at,
      workflow_status: 'VALIDADO',
      validado_gestao: true,
      validado_por: 'USR-QUALITY-001',
      validado_em: at,
      devolvido_por: null,
      devolvido_em: null,
      devolvido_motivo: null,
      enviado_validacao_em: at,
      revisao: 1,
      setor_id: 'SECTOR-001',
      modelo_base_id: null,
      revisao_origem_id: null,
      substitui_plano_id: null,
      substituido_por: null,
      substituido_em: null,
      modo_parada_manutencao: 'MANDATORY_STOP',
      analise_tecnica_json: '{}',
      analise_origem_id: null,
      ocorrencia_origem_id: null,
    },
  ],
  plano_itens: [
    {
      id: 'ITEM-001',
      plano_id: 'PLAN-001',
      ordem: 1,
      titulo: 'Inspecionar rolamento',
      instrucao: 'Registrar a condição e uma evidência.',
      tipo_resposta: 'OK_NOK',
      obrigatorio: true,
      evidencia_obrigatoria: true,
      foto_referencia_url: null,
      limite_min: null,
      limite_max: null,
      unidade: null,
      criado_em: at,
      atualizado_em: at,
      parametro_nome: null,
      valor_esperado: 'OK',
      opcoes_json: '[]',
      bloqueia_finalizacao: true,
      categoria: 'SAFETY',
      peso: 1,
      status: 'ACTIVE',
      validacao_regra: null,
      evidencia_min_fotos: 1,
    },
  ],
  plano_controle: [
    {
      plano_id: 'PLAN-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      gatilho_tipo: 'MANUAL',
      gatilho_valor: null,
      ultimo_valor_processado: 1200,
      proximo_valor_gatilho: 1230,
      ultima_acao_id: 'ACTION-001',
      ultima_acao_status: 'COMPLETED',
      atualizado_em: later,
    },
  ],
  ordens_servico: [
    {
      id: 'WO-001',
      codigo: 'OS-MIG-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      plano_id: 'PLAN-001',
      origem: 'PLAN',
      tipo: 'PREVENTIVE',
      titulo: 'Inspeção programada',
      descricao: 'Inspeção completa do motor.',
      prioridade: 'HIGH',
      status: 'COMPLETED',
      solicitante_id: 'USR-ADMIN-001',
      responsavel_id: 'USR-OPERATOR-001',
      aberta_em: at,
      planejada_para: at,
      iniciada_em: at,
      finalizada_em: later,
      criado_em: at,
      atualizado_em: later,
      modo_parada_manutencao: 'MANDATORY_STOP',
      analise_tecnica_json: '{}',
    },
  ],
  os_acoes: [
    {
      id: 'ACTION-001',
      os_id: 'WO-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      plano_id: 'PLAN-001',
      origem: 'PLAN',
      tipo: 'PREVENTIVE',
      titulo: 'Executar inspeção',
      descricao: 'Executar checklist aprovado.',
      prioridade: 'HIGH',
      status: 'COMPLETED',
      responsavel_id: 'USR-OPERATOR-001',
      gerado_em: at,
      iniciado_em: at,
      finalizado_em: later,
      atualizado_em: later,
      modo_parada_manutencao: 'MANDATORY_STOP',
      analise_tecnica_json: '{}',
    },
  ],
  execucoes: [
    {
      id: 'EXEC-001',
      acao_id: 'ACTION-001',
      os_id: 'WO-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      operador_id: 'USR-OPERATOR-001',
      resultado: 'COMPLETED',
      observacao: 'Inspeção concluída.',
      duracao_segundos: 3600,
      abriu_em: at,
      iniciou_em: at,
      finalizou_em: later,
      status: 'COMPLETED',
      criado_em: at,
      atualizado_em: later,
      modo_execucao_manutencao: 'STOPPED',
    },
  ],
  checklist_execucao: [
    {
      id: 'EXEC-ITEM-001',
      execucao_id: 'EXEC-001',
      acao_id: 'ACTION-001',
      plano_item_id: 'ITEM-001',
      ordem: 1,
      titulo: 'Inspecionar rolamento',
      instrucao: 'Registrar a condição.',
      tipo_resposta: 'OK_NOK',
      obrigatorio: true,
      resposta: 'OK',
      observacao: 'Sem anormalidades.',
      evidencia_obrigatoria: true,
      status: 'COMPLETED',
      responsavel_id: 'USR-OPERATOR-001',
      data_hora: later,
      criado_em: at,
      atualizado_em: later,
      parametro_nome: null,
      valor_esperado: 'OK',
      opcoes_json: '[]',
      limite_min: null,
      limite_max: null,
      unidade: null,
      valor_numero: null,
      conforme: true,
      bloqueia_finalizacao: true,
      validacao_msg: null,
      evidencias_count: 1,
      categoria: 'SAFETY',
      evidencia_min_fotos: 1,
    },
  ],
  evidencias: [
    {
      id: 'EVIDENCE-001',
      execucao_id: 'EXEC-001',
      acao_id: 'ACTION-001',
      checklist_execucao_id: 'EXEC-ITEM-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      tipo: 'PHOTO',
      nome_arquivo: 'inspection.jpg',
      url: 'https://legacy.invalid/inspection.jpg',
      observacao: 'Evidência legada.',
      usuario_id: 'USR-OPERATOR-001',
      criado_em: later,
      arquivo_id: 'FILE-EVIDENCE-001',
      mime_type: 'image/jpeg',
      tamanho_bytes: 1024,
      thumbnail_url: 'https://legacy.invalid/inspection-thumb.jpg',
    },
  ],
  materiais_uso: [
    {
      id: 'USAGE-001',
      execucao_id: 'EXEC-001',
      acao_id: 'ACTION-001',
      material_id: 'MAT-001',
      quantidade: 0.5,
      unidade: 'kg',
      observacao: 'Lubrificação.',
      usuario_id: 'USR-OPERATOR-001',
      criado_em: later,
    },
  ],
  parametros: [
    {
      id: 'READING-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      parametro: 'Temperatura',
      valor: 55,
      unidade: '°C',
      origem: 'MANUAL',
      registrado_por: 'USR-QUALITY-001',
      registrado_em: later,
      criado_em: later,
    },
  ],
  paradas_equipamento: [
    {
      id: 'STOP-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      os_id: 'WO-001',
      acao_id: 'ACTION-001',
      execucao_id: 'EXEC-001',
      origem: 'MAINTENANCE',
      tipo: 'PLANNED',
      status: 'COMPLETED',
      iniciada_em: at,
      iniciada_por: 'USR-OPERATOR-001',
      manutencao_iniciada_em: at,
      manutencao_finalizada_em: later,
      finalizada_em: later,
      finalizada_por: 'USR-OPERATOR-001',
      tempo_parada_segundos: 3600,
      tempo_espera_manutencao_segundos: 0,
      tempo_execucao_segundos: 3600,
      tempo_retorno_operacional_segundos: 0,
      motivo_parada: 'Inspeção programada',
      categoria_retorno: 'NORMAL',
      justificativa_divergencia: null,
      tolerancia_retorno_min: 10,
      criado_em: at,
      atualizado_em: later,
    },
  ],
  paradas_manutencao: [
    {
      id: 'MSTOP-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      os_id: 'WO-001',
      acao_id: 'ACTION-001',
      execucao_id: 'EXEC-001',
      modo_configurado: 'MANDATORY_STOP',
      decisao_execucao: 'STOP',
      status: 'COMPLETED',
      equipamento_ja_parado: false,
      alterou_status_ativo: true,
      iniciada_em: at,
      finalizada_em: later,
      duracao_segundos: 3600,
      usuario_id: 'USR-OPERATOR-001',
      criado_em: at,
      atualizado_em: later,
    },
  ],
  ocorrencias_operacionais: [
    {
      id: 'OCC-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      tipo: 'NOISE',
      titulo: 'Ruído no rolamento',
      descricao: 'Ruído acima do habitual.',
      severidade: 'HIGH',
      status: 'CLOSED',
      usuario_id: 'USR-OPERATOR-001',
      perfil: 'OPERATOR',
      os_id: 'WO-001',
      acao_id: 'ACTION-001',
      parada_id: 'STOP-001',
      demanda_tecnica_id: 'DEMAND-001',
      analise_tecnica_id: 'ANALYSIS-001',
      tratamento_status: 'COMPLETED',
      criado_em: at,
      atualizado_em: later,
    },
  ],
  areas_tecnicas: [
    {
      id: 'AREA-QUALITY',
      codigo: 'QUALIDADE',
      nome: 'Qualidade',
      descricao: 'Validação técnica',
      status: 'ACTIVE',
      exige_assinatura_padrao: true,
      criado_por: 'USR-ADMIN-001',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  cargos_tecnicos: [
    {
      id: 'ROLE-INSPECTOR',
      area_id: 'AREA-QUALITY',
      codigo: 'QUALITY_INSPECTOR',
      nome: 'Inspetor de qualidade',
      descricao: 'Assinatura de qualidade',
      status: 'ACTIVE',
      pode_assinar: true,
      criado_por: 'USR-ADMIN-001',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  demandas_tecnicas: [
    {
      id: 'DEMAND-001',
      tipo: 'CHECKLIST_REVIEW',
      entidade_tipo: 'WORK_ORDER',
      entidade_id: 'WO-001',
      origem_tipo: 'OCCURRENCE',
      origem_id: 'OCC-001',
      titulo: 'Validar inspeção',
      descricao: 'Validar o checklist e a evidência.',
      prioridade: 'HIGH',
      status: 'COMPLETED',
      area_origem_id: 'AREA-QUALITY',
      area_atual_id: 'AREA-QUALITY',
      cargo_atual_id: 'ROLE-INSPECTOR',
      responsavel_atual_id: 'USR-QUALITY-001',
      criado_por: 'USR-ADMIN-001',
      criado_perfil: 'ADMIN',
      exige_assinatura: true,
      assinaturas_necessarias: 1,
      assinaturas_realizadas: 1,
      exige_segregacao: true,
      politica_assinatura: 'QUALIDADE',
      areas_validadoras_json: '["AREA-QUALITY"]',
      usuarios_validadores_json: '[]',
      prazo_primeira_resposta_em: later,
      prazo_resolucao_em: later,
      primeiro_atendimento_em: at,
      concluido_em: later,
      versao_entidade: 1,
      payload_hash: 'a'.repeat(64),
      criado_em: at,
      atualizado_em: later,
    },
  ],
  demanda_tramitacoes: [
    {
      id: 'EVENT-001',
      demanda_id: 'DEMAND-001',
      sequencia: 1,
      acao: 'APPROVE',
      de_area_id: 'AREA-QUALITY',
      de_cargo_id: 'ROLE-INSPECTOR',
      de_usuario_id: 'USR-QUALITY-001',
      para_area_id: null,
      para_cargo_id: null,
      para_usuario_id: 'USR-ADMIN-001',
      decisao: 'APPROVED',
      parecer: 'Checklist aprovado.',
      motivo: null,
      payload_hash: 'event-hash',
      criado_em: later,
    },
  ],
  assinaturas_tecnicas: [
    {
      id: 'SIGNATURE-001',
      demanda_id: 'DEMAND-001',
      entidade_tipo: 'WORK_ORDER',
      entidade_id: 'WO-001',
      versao_entidade: 1,
      usuario_id: 'USR-QUALITY-001',
      perfil: 'GESTOR',
      area_id: 'AREA-QUALITY',
      cargo_id: 'ROLE-INSPECTOR',
      significado: 'APPROVAL',
      declaracao: 'Aprovado tecnicamente.',
      payload_hash: 'a'.repeat(64),
      criado_em: later,
      revogado_em: null,
      motivo_revogacao: null,
    },
  ],
  analises_tecnicas: [
    {
      id: 'ANALYSIS-001',
      demanda_id: 'DEMAND-001',
      ocorrencia_id: 'OCC-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      autor_id: 'USR-QUALITY-001',
      area_id: 'AREA-QUALITY',
      cargo_id: 'ROLE-INSPECTOR',
      titulo: 'Análise do rolamento',
      diagnostico: 'Inspeção concluída.',
      risco: 'Baixo após manutenção.',
      causa_provavel: 'Lubrificação insuficiente',
      recomendacao: 'Manter inspeção mensal.',
      recomenda_checklist: true,
      recomenda_os: false,
      prioridade: 'MEDIUM',
      status: 'ACCEPTED',
      enviado_admin_em: later,
      criado_em: at,
      atualizado_em: later,
      relatorio_tecnico_json: '{"safety":["LOTO"]}',
    },
  ],
  notificacoes: [
    {
      id: 'NOTIFICATION-001',
      usuario_id: 'USR-ADMIN-001',
      perfil: 'ADMIN',
      area_id: null,
      tipo: 'DEMAND_COMPLETED',
      titulo: 'Validação concluída',
      mensagem: 'A demanda foi aprovada.',
      entidade_tipo: 'WORK_ORDER',
      entidade_id: 'WO-001',
      prioridade: 'INFO',
      status: 'ACTIVE',
      lida_em: later,
      criado_em: at,
    },
  ],
  turnos: [
    {
      id: 'SHIFT-001',
      planta_id: 'PLANT-001',
      setor_id: 'SECTOR-001',
      linha_id: 'LINE-001',
      nome: 'Turno A',
      inicio_hora: '06:00',
      fim_hora: '14:00',
      dias_semana_json: '[1,2,3,4,5]',
      timezone: 'America/Sao_Paulo',
      status: 'ACTIVE',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  apontamentos_producao: [
    {
      id: 'PRODUCTION-001',
      turno_id: 'SHIFT-001',
      ativo_id: 'ASSET-001',
      inicio_em: at,
      fim_em: later,
      tempo_planejado_segundos: 3600,
      tempo_operacao_segundos: 3500,
      ciclo_ideal_segundos: 10,
      quantidade_total: 340,
      quantidade_boas: 335,
      quantidade_refugo: 5,
      fonte: 'MANUAL',
      usuario_id: 'USR-OPERATOR-001',
      criado_em: at,
      atualizado_em: later,
    },
  ],
  sla_politicas: [
    {
      id: 'SLA-001',
      tipo_demanda: 'CHECKLIST_REVIEW',
      prioridade: 'HIGH',
      area_id: 'AREA-QUALITY',
      resposta_minutos: 30,
      resolucao_minutos: 240,
      calendario_id: 'DEFAULT',
      status: 'ACTIVE',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  historico: [
    {
      id: 'HISTORY-001',
      ativo_id: 'ASSET-001',
      componente_id: 'COMP-001',
      os_id: 'WO-001',
      acao_id: 'ACTION-001',
      execucao_id: 'EXEC-001',
      evento: 'EXECUTION_COMPLETED',
      descricao: 'Execução concluída e auditada.',
      usuario_id: 'USR-OPERATOR-001',
      perfil: 'OPERATOR',
      criado_em: later,
    },
  ],
  execucao_locks: [
    {
      id: 'LOCK-001',
      ativo_id: 'ASSET-001',
      acao_id: 'ACTION-001',
      usuario_id: 'USR-OPERATOR-001',
      sessao_id: 'LEGACY-SESSION-001',
      status: 'RELEASED',
      adquirido_em: at,
      ultimo_ping_em: at,
      expira_em: later,
      liberado_em: later,
      motivo_liberacao: 'COMPLETED',
      user_agent: 'fixture',
    },
  ],
  telemetria_sessoes: [
    {
      id: 'TELEMETRY-001',
      sessao_id: 'LEGACY-SESSION-001',
      usuario_id: 'USR-ADMIN-001',
      ativo_id: 'ASSET-001',
      acao_id: 'ACTION-001',
      evento: 'VIEW',
      visibilidade: 'VISIBLE',
      delta_segundos: 30,
      tempo_total_segundos: 30,
      tempo_visivel_segundos: 30,
      tempo_oculto_segundos: 0,
      user_agent: 'fixture',
      criado_em: at,
    },
  ],
  audit_log: [
    {
      id: 'AUDIT-001',
      usuario_id: 'USR-ADMIN-001',
      perfil: 'ADMIN',
      acao: 'MIGRATION_TEST',
      entidade: 'ASSET',
      entidade_id: 'ASSET-001',
      antes_json: '{}',
      depois_json: '{"status":"OPERATING"}',
      user_agent: 'fixture',
      criado_em: at,
    },
  ],
  checklist_modelo_validacoes: [
    {
      id: 'REVIEW-001',
      plano_id: 'PLAN-001',
      revisao: 1,
      decisao: 'APPROVED',
      justificativa: 'Modelo aprovado.',
      usuario_id: 'USR-QUALITY-001',
      perfil: 'GESTOR',
      criado_em: at,
    },
  ],
  checklist_tipos_item: [
    {
      id: 'TYPE-001',
      tipo: 'OK_NOK',
      nome: 'Conforme ou não conforme',
      descricao: 'Decisão controlada',
      requer_resposta: true,
      requer_valor: false,
      requer_opcoes: false,
      suporta_limite: false,
      suporta_evidencia: true,
      categoria_padrao: 'OPERATIONAL',
      ativo: true,
      criado_em: at,
    },
  ],
  checklist_validacao_regras: [
    {
      id: 'RULE-001',
      tipo_item: 'OK_NOK',
      codigo: 'REQUIRE_OK',
      nome: 'Exigir conformidade',
      descricao: 'Bloqueia resposta não conforme.',
      regra_json: '{"equals":"OK"}',
      ativo: true,
      criado_em: at,
    },
  ],
  modelo_checklist_auditoria: [
    {
      id: 'MODEL-AUDIT-001',
      plano_id: 'PLAN-001',
      item_id: 'ITEM-001',
      evento: 'ITEM_CREATED',
      antes_json: '{}',
      depois_json: '{"titulo":"Inspecionar rolamento"}',
      usuario_id: 'USR-ADMIN-001',
      perfil: 'ADMIN',
      criado_em: at,
    },
  ],
  dashboard_cache: [
    { chave: 'technical-dashboard', valor_json: '{}', gerado_em: at, ttl_segundos: 60 },
  ],
  configuracao_versoes: [
    {
      id: 'CONFIG-V1',
      numero: 1,
      status: 'PUBLISHED',
      origem: 'ADMIN',
      base_versao_id: null,
      configuracao_json: '{"validation":{"quality":true}}',
      hash_sha256: 'config-hash',
      validacao_json: '{"valid":true}',
      criado_por: 'USR-ADMIN-001',
      criado_em: at,
    },
  ],
  configuracao_rascunhos: [
    {
      id: 'CONFIG-DRAFT-001',
      usuario_id: 'USR-ADMIN-001',
      base_versao_id: 'CONFIG-V1',
      configuracao_json: '{"validation":{"quality":true}}',
      hash_sha256: 'draft-hash',
      validacao_json: '{"valid":true}',
      status: 'VALID',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  importacao_lotes: [
    {
      id: 'IMPORT-001',
      tipo: 'STRUCTURE',
      entidade: 'ASSET',
      arquivo_nome: 'assets.xlsx',
      aba_nome: 'ativos',
      status: 'CONFIRMED',
      total_linhas: 1,
      linhas_validas: 1,
      linhas_invalidas: 0,
      validacao_hash: 'import-hash',
      cabecalhos_json: '["id","tag"]',
      cabecalhos_ignorados_json: '[]',
      resultado_json: '{"created":1}',
      criado_por: 'USR-ADMIN-001',
      criado_em: at,
      confirmado_por: 'USR-ADMIN-001',
      confirmado_em: later,
      rollback_por: null,
      rollback_em: null,
      atualizado_em: later,
    },
  ],
  importacao_registros: [
    {
      id: 'IMPORT-ROW-001',
      lote_id: 'IMPORT-001',
      linha_numero: 2,
      entidade: 'ASSET',
      entidade_id: 'ASSET-001',
      operacao: 'CREATE',
      status: 'APPLIED',
      raw_json: '{"tag":"EQ-001"}',
      normalizado_json: '{"tag":"EQ-001"}',
      erros_json: '[]',
      antes_json: '{}',
      depois_json: '{"id":"ASSET-001"}',
      aplicado_em: later,
      rollback_em: null,
      criado_em: at,
      atualizado_em: later,
    },
  ],
  documentos_tecnicos: [
    {
      id: 'DOCUMENT-001',
      codigo: 'DOC-001',
      titulo: 'Procedimento de inspeção',
      tipo: 'PROCEDURE',
      entidade_tipo: 'ASSET',
      entidade_id: 'ASSET-001',
      status: 'ACTIVE',
      revisao_atual: 1,
      validade_em: '2027-08-04',
      responsavel_id: 'USR-QUALITY-001',
      descricao: 'Procedimento técnico.',
      arquivo_id: 'FILE-DOC-001',
      arquivo_nome: 'procedure.pdf',
      mime_type: 'application/pdf',
      tamanho_bytes: 2048,
      criado_por: 'USR-ADMIN-001',
      criado_em: at,
      atualizado_em: at,
    },
  ],
  documento_revisoes: [
    {
      id: 'DOCUMENT-REV-001',
      documento_id: 'DOCUMENT-001',
      revisao: 1,
      arquivo_id: 'FILE-DOC-001',
      arquivo_nome: 'procedure.pdf',
      mime_type: 'application/pdf',
      tamanho_bytes: 2048,
      observacao: 'Primeira revisão.',
      criado_por: 'USR-ADMIN-001',
      criado_em: at,
    },
  ],
  legado_quarentena: [
    {
      id: 'QUARANTINE-001',
      aba_origem: 'legacy_unknown',
      linha_origem: '2',
      motivo: 'Registro histórico preservado.',
      payload_json: '{"legacy":true}',
      movido_em: at,
    },
  ],
};

export async function createMigrationFixture(filePath: string): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  for (const contract of sourceSheetContracts) {
    const worksheet = workbook.addWorksheet(contract.name);
    worksheet.addRow([...contract.headers]);
    for (const sourceRow of rows[contract.name] ?? []) {
      worksheet.addRow(contract.headers.map((header) => sourceRow[header] ?? null));
    }
  }
  await workbook.xlsx.writeFile(filePath);
}
