export interface BackupTable {
  readonly name: string;
}

export const BACKUP_FORMAT = 'FAB_CONTROL_TENANT_BACKUP_V1';

// Ordem de inserção respeita as dependências; a exclusão usa a ordem inversa.
export const backupTables: readonly BackupTable[] = Object.freeze(
  [
    'cmms.plants',
    'cmms.sectors',
    'cmms.lines',
    'cmms.assets',
    'cmms.components',
    'cmms.materials',
    'cmms.parameter_definitions',
    'cmms.parameter_policies',
    'cmms.parameter_readings',
    'maintenance.checklist_templates',
    'maintenance.checklist_template_versions',
    'maintenance.checklist_version_validator_users',
    'maintenance.checklist_items',
    'maintenance.checklist_model_reviews',
    'maintenance.checklist_model_audit',
    'maintenance.maintenance_plans',
    'maintenance.maintenance_plan_versions',
    'maintenance.work_orders',
    'maintenance.plan_trigger_state',
    'maintenance.work_order_actions',
    'maintenance.executions',
    'maintenance.execution_checklist_items',
    'maintenance.evidence',
    'maintenance.material_usage',
    'maintenance.equipment_stops',
    'maintenance.maintenance_stops',
    'maintenance.operational_occurrences',
    'maintenance.operational_alerts',
    'maintenance.history_events',
    'maintenance.execution_locks',
    'maintenance.telemetry_sessions',
    'maintenance.shifts',
    'maintenance.production_entries',
    'workflow.service_calendars',
    'workflow.service_calendar_windows',
    'workflow.service_calendar_holidays',
    'workflow.sla_policies',
    'workflow.technical_demands',
    'workflow.demand_validator_requirements',
    'workflow.demand_events',
    'workflow.technical_signatures',
    'workflow.technical_signature_revocations',
    'workflow.technical_analyses',
    'workflow.notifications',
    'workflow.notification_recipients',
    'governance.technical_documents',
    'governance.document_revisions',
    'governance.import_batches',
    'governance.import_records',
    'governance.legacy_quarantine',
  ].map((name) => Object.freeze({ name })),
);

export const protectedBackupDomains = Object.freeze([
  'Identidades, credenciais e sessões',
  'Perfis, capacidades e permissões',
  'Assinaturas comerciais e recursos de plano',
  'Configuração publicada e janelas de manutenção',
  'Trilha de auditoria imutável',
  'Metadados dos próprios backups',
]);
